vuejs/vue-loader

index.js

Support for async parsers as current version was breaking for less scripts when in sync mode.

Support for async parsers.

---

docs/features/postcss.md

cssnext has [became](http://cssnext.io/postcss/#wait-what-is-postcss) a simple plugin of postcss.

change "cssnext" to "postcss-cssnext"

---

docs/en/start/tutorial.md

Update main.js to comply with App.vue example.

Use ES6 in main.js

---

docs/en/start/spec.md

add JetBrains vue plugins

---

lib/loader.js

Signed-off-by: Ken Vu <ken@gladeye.co.nz>

Fix: `browserify` flag should be false

---

lib/parser.js
test/test.js

Re: #190 – Padded the output to get line numbers accurate. Not sure if this is the correct strategy or not. Also did not test the effects on source maps.

pad results with whitespace - re #190

---

lib/template-loader.js

prevent webpack crashing when templateLoader compiled errors.
https://github.com/vuejs/vue-cli/issues/111

shold emit webpack Error rather than throwing

---

docs/en/features/es2015.md

Change a character 'babel-laoder' to 'babel-loader'

Change a character at line 33

---

docs/en/features/es2015.md

Minor typo

---

docs/en/workflow/linting.md

Here's the documentation for the changes:
https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23
https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.24

Add Webpack 2.x configuration for eslint

---

docs/en/configurations/pre-processors.md

Explain SASS caveat

---

docs/en/options.md
lib/template-compiler.js
package.json
test/fixtures/transform.vue
test/test.js

ref: https://github.com/vuejs/vue-loader/issues/569#issuecomment-271710412
@yyx990803 said 💬 
>We may consider adding this to default config.
@vuejs/vue-loader-vueify 
Please review ! 👀

Add 'image' tag of SVG to 'transformToRequire` option as default

---

docs/en/start/spec.md

add component name section to spec docs

---

lib/loader.js

This was ported from the master branch (Vue 2.x Loader)

Read options in a way that works even for Webpack 2.2

---

docs/en/configurations/pre-processors.md

fix(docs): Correct Tiny Typo

---

docs/en/start/spec.md

Removing second `by` in last sentence

- Fix typo

---

lib/loader.js
test/test.js

support webpack2 and extract-text-webpack-plugin 2

---

lib/style-rewriter.js

/related https://github.com/postcss/postcss-loader/pull/174

Do not load config file from `--config`

---

docs/en/README.md

Missing word

---

lib/loader.js
lib/selector.js
lib/style-rewriter.js
lib/template-loader.js
lib/template-rewriter.js
package.json

fix deprecated warning for 8.x

---

docs/pt_BR/configurations/pre-processors.md

Corrigindo escrita de "Unsando" por "Usando".

Corrigindo escrita de palavra

---

docs/en/configurations/pre-processors.md

tiny fix, just missing comma in JSON example

add missing comma

---

docs/pt_BR/configurations/custom-blocks.md
docs/ru/configurations/custom-blocks.md

Ref: https://github.com/vuejs/vue-loader/pull/699

[Docs] Updated

---

lib/style-compiler/load-postcss-config.js

Reverts vuejs/vue-loader#738
See:
https://travis-ci.org/nuxt/nuxt.js/jobs/214683257

Revert "Change let to var"

---

lib/loader.js
package.json
test/fixtures/custom-blocks.vue
test/mock-loaders/blog.js
test/mock-loaders/i18n.js
test/mock-loaders/yaml.js
test/test.js

support pre/post loaders for custom blocks

---

docs/zh-cn/start/spec.md

Fixed typo

---

docs/pt_BR/workflow/production.md

Ref: https://github.com/vuejs/vue-loader/pull/760

[Docs] Add note about OccurrenceOrderPlugin

---

lib/loader.js

fix: https://github.com/vuejs/vue-loader/issues/759

Do not consider private properties to be named exports

---

docs/pt_BR/README.md

Please, consider reviewing the following changes for PT_BR translation in order to improve the comprehension for non-English speakers.

Improving PT BR translation for some sentences

---

docs/en/start/spec.md

minor typo edit

---

docs/en/workflow/linting.md
docs/ja/workflow/linting.md
docs/kr/workflow/linting.md
docs/pt_BR/workflow/linting.md
docs/ru/workflow/linting.md
docs/zh-cn/workflow/linting.md

fix incorrect regexp

---

docs/en/configurations/pre-processors.md

per this comment thread: https://github.com/vuejs/vue-loader/issues/328#issuecomment-311579950
This is my first open source contribution :o Let me know if the verbiage is OK, and also not sure how updating other languages works.

update docs for global scss loading

---

docs/pt_BR/workflow/testing-with-mocks.md

Ref: https://github.com/vuejs/vue-loader/pull/837/files

Use `vue-loader` explictly when creating injector

---

docs/pt_BR/features/scoped-css.md

Ref: https://github.com/vuejs/vue-loader/pull/841

Added info about deep selectors

---

lib/template-compiler/index.js
yarn.lock

seems we can't use `module.exports` while using `esModule` format, not sure if this is the correct fix though.

Fix template hmr, fix #863

---

docs/pt_BR/features/hot-reload.md

Correção texto "proto" para uso " por "pronto" para uso na linha 7.

Correção texto

---

lib/loader.js

fix css module HMR

---

lib/style-compiler/plugins/scope-id.js
test/fixtures/supports-query.vue
test/test.js

Added testing for @supports as well
fixes #906

Adds support for scoped selectors in @supports queries

---

lib/template-compiler/index.js
test/fixtures/custom-directive.vue
test/test.js

add vue-template-compiler options passing for v12

---

lib/loader.js

remove unnecessary blank space for better output string

---

lib/loader.js

[Fixed #1064] supported ES default exported function for custom block in runtime

---

lib/loader.js

[wip]: Will add some test cases.
ref: #1080 
Thanks.

Supported named exports #1080

---

docs/zh-cn/README.md
docs/zh-cn/configurations/advanced.md
docs/zh-cn/configurations/asset-url.md
docs/zh-cn/configurations/custom-blocks.md
docs/zh-cn/configurations/extract-css.md
docs/zh-cn/configurations/pre-processors.md
docs/zh-cn/features/es2015.md
docs/zh-cn/features/postcss.md
docs/zh-cn/options.md
docs/zh-cn/start/spec.md
docs/zh-cn/workflow/linting.md
docs/zh-cn/workflow/production.md
docs/zh-cn/workflow/testing-with-mocks.md
docs/zh-cn/workflow/testing.md

... from #cda4973 to #ebd66fe
Ref: https://github.com/vuejs/vue-loader/compare/cda4973...ebd66fe
/ping @Justineo 
Thanks.

[docs][zh-cn] synced updates

---

lib/style-compiler/load-postcss-config.js
test/test.js

[fixed #965] more friendly error message for loading PostCSS config

---

docs/zh-cn/options.md

In about details, see more directives option of vue-template-compiler.
相关细节请查阅 vue-template-compiler 的 modules 选项。 => 相关细节请查阅 vue-template-compiler 的 directives 选项。

modules 选项 => directives 选项

---

docs/en/SUMMARY.md
docs/ja/SUMMARY.md
docs/ru/SUMMARY.md
docs/zh-cn/SUMMARY.md

docs: remove cacheBusting from table of contents

---

docs/en/options.md
docs/zh-cn/SUMMARY.md
docs/zh-cn/options.md

https://github.com/vuejs/vue-loader/compare/b22db1d...f06e3e7
/ping @Justineo 
Thanks

[docs][zh-cn] translated recent updates

---

docs/en/start/spec.md

I'm learning Vue and had to look up what these options were, so I thought it might be helpful to direct others to the appropriate docs page.

Added link to component options spec

---

lib/plugin.js

fix: reuse ident of vue-style-loader

---

docs/guide/extract-css.md

[docs][v15]: Add quotes around filename for v4

---

docs/zh/guide/custom-blocks.md
docs/zh/options.md

Ref: https://github.com/vuejs/vue-loader/compare/d3041e7...2124596

[docs][zh] updated to 2124596

---

docs/guide/README.md

Just a very minor grammar correction.

Small typo correction. Changed form to from

---

lib/codegen/hotReload.js

This PR also contains very small tweaks.

chore: avoid using templates literals for string constants

---

docs/zh/guide/testing.md

fix a wrong link which should direct to vue-test-utils doc site.

(docs): fix a wrong link.

---

lib/codegen/styleInjection.js
test/fixtures/css-modules-extend.vue
test/style.spec.js

fix: css modules extends error

---

docs/guide/README.md

docs: add a warning that css is considered as a side effect

---

docs/zh/guide/extract-css.md

docs: loss of quotes

---

docs/guide/asset-url.md
docs/options.md
docs/ru/guide/asset-url.md
docs/ru/options.md
docs/zh/guide/asset-url.md
docs/zh/options.md

See https://github.com/vuejs/component-compiler-utils/blob/master/lib/templateCompilerModules/assetUrl.ts#L9

Correct the docs for the default value of transformAssetUrls

---

docs/guide/custom-blocks.md

fix: end of tag

---

test/utils.js

chore: Invoke createFsFromVolume as a regular function

---

docs/guide/pre-processors.md

When I tried this example by copy-and-paste, I figured out there was a syntax error.

Fix an example code

---

lib/index.js

Maybe this is trivial, but removing that makes the code looks better :)

chore: remove temporary unused code

---

src/hotReload.ts

https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/hmr.ts#L61

style: `createRecord` only accepts a single param

---

README.md

Fixes some mistakes in 'How It Works' chapter.

docs: fix mistakes in README

---

docs/guide/scoped-css.md

Hi,
this is just a small documentation update in relation to deep selectors. I stumbled upon the alternative expressions and it was unclear how these should be applied.
Thank you for your time!

docs: illustrate usage of alternative deep selector expressions

---

package.json

This reference makes it easier to discover the source repo.

Add `repository` property to package.json

---

src/pluginWebpack5.ts

https://github.com/vuejs/vue-loader/issues/1849
fix thanks to @nskazki

fix: do not throw when `Rule.layer`

---

src/index.ts

fix #2028, full credit goes to @alexander-akait, thank you!
I have tested this fix and I can confirm the original issue is fixed with it.

fix: keep build stable when run in a different path

---

lib/index.js

fix: fix read property error for accessing lang of script
