lib/parser.js, test/test.js
this PR will keep and comment all non-script source code in scripts output,
thus it will preserve line number and be friendly to linters(include file newLine ending).
=> Preserve line number for linters

lib/loader.js, lib/parser.js, test/fixtures/script-import-entry.js, test/fixtures/script-import.js, test/fixtures/script-import.vue, test/test.js
The intention of this PR is to have *.vue files as entry points for components, but the code separated across the js/html/css files and have all the benefits of vue-loader, such as hot-reload
=> Support "src" attribute for script tag

lib/style-rewriter.js, test/test.js
1. Allow postcss options to be a function and close issue #106.
2. In node v5.0.0, the error param for `fs.readFile`'s callback is `undefined`, not `null`:)
=> Allow postcss options to be a function and close issue #106

lib/loader.js
move `defaultLoaders` to module.exports to prevent that in mutiple webpack build situations, previous `defaultLoaders` configuration will be cached and apply to following builds, which would ignore following `webpack.vue` options such as `cssSourceMap: false`
=> move `defaultLoaders` to module.exports

docs/start/spec.md
Closes https://github.com/vuejs/vue-loader/issues/159
=> Comments section in the Vue Component Spec doc

docs/configurations/pre-processors.md
node-sass is not beeing installed with sass-loader, so it has to be
added to the command
=> node-sass dependency

docs/en/configurations/pre-processors.md
Before:
"...template loaders ... **returns** a template function instead of compiled HTML string."
After:
"...template loaders ... **return** a template function instead of **a** compiled HTML string."
=> "return" vs "returns" and added an "a"

lib/style-rewriter.js
Global variables (`currentId`) should not be used for passing arguments to "execute-later" async functions.
This patch fixes a hard-to-reproduce bug, which is described below.
For example, I have two vue component `foo.vue` and `bar.vue` and they both have the same content as below:
```html
<template>
<div class="hello"></div>
</template>
<style scoped>
.hello { display: none; }
</style>
```
When I use them like this:
```html
<foo></foo>
<bar></bar>
```
It produces HTML as following
```html
<div class="hello" _v-1234567></div>
<div class="hello" _v-2222222></div>
```
This is correct. But on the style side, you get the following with some setup
```css
.hello[_v-2222222] { display: none; }    /* from foo.vue, the id should be _v-1234567 */
.hello[_v-2222222] { display: none; }    /* from …
```
=> pass query.id as an option to addId in style-rewriter

lib/template-loader.js
Merges `vue.template` with the HTML preprocessor query string.
=> Enable passing options to the template engine

lib/style-rewriter.js
I wanted to use SugarSS with PostCSS with vue-loader. It wasn't possible without modifying the style-rewriter and changing the way options works.
You still can use the 
`postcss: array of plugins`
`postcss: function that return array of plugins`
or the new one
```
postcss: {
plugins: array of plugins,
syntax: custom syntax, like sugarss
}
```
Allowing the use of sugarss or others syntax as custom postcss syntax with vue loader.
=> Allow vue-loader to user PostCSS options as object and custom syntax

lib/loader.js
I'm new to all this, but any reason we're not using [stringifyRequest](https://github.com/webpack/loader-utils#stringifyrequest) from `loader-utils`? The current approach results in machine-specific absolute paths in the generated bundle.
https://webpack.github.io/docs/how-to-write-a-loader.html#should-not-embed-absolute-paths
=> Use loaderUtils.stringifyRequest for relative path

docs/en/workflow/linting.md
I saw the text is `eslint-html-plugin` while that package names `eslint-plugin-html`.
Maybe a typo?
=> `eslint-html-plugin` to `eslint-plugin-html`

lib/loader.js, package.json, test/fixtures/extend.vue, test/test.js
This patch fixes #340.
We are checking `typeof __vue_exports__.default` for ES6 modules interop but only checking whether it is an object or not.
If we export Vue constructor (`export default Vue.extend({...})`), the check is failed and it exports incorrect object.
I have add `typeof __vue_exports__.default === 'function'` to handle such situation.
=> allow to export constructor even if using es6 default export

docs/en/options.md, lib/loader.js, test/test.js
This pull request adds an alternative module export mechanism.
For [some language](https://github.com/Microsoft/TypeScript/issues/2242), `export default ...` is not transpiled to `module.exports = ....`.
When `vue` option's `esModule` is set to `true`, vue-loader will produce code like below:
```js
exports.__esModule = true
exports["default"] = __vue_exports__
```
I think some tests and docs are needed. If you think this approach is acceptable, please let me know and I will add required tests.
=> add esModule support

docs/en/workflow/testing.md
The top of the page contains the correct link, but this reference is still outdated.
=> Fix link to deprecated example repo

lib/loader.js
The current way to handle Webpack 2 Beta 24+ involves the use of `LoaderOptionsPlugin`. This is non-ideal, as `LoaderOptionsPlugin` actually mangles `this.options` in loaders to refer to its configuration instead of what webpack normally passes. Because of this, `LoaderOptionsPlugin` should be used only as a stopgap until a fix is introduced to make the loader compatible with Webpack 2 Beta 24+ by loading its options from `this.query` instead of `this.options.x`.
[Current Usage](https://github.com/vuejs/vue-hackernews-2.0/blob/master/build/webpack.base.config.js#L38-L40) (`LoaderOptionsPlugin`):
```javascript
module.exports = {
...
module: {
rules: [
{
test: /\.vue$/,
loader: 'vue'
},
...
]
},
plugins: [
new webpack.LoaderOptionsPlugin({
vue: {
...
}
})
]
}
```
[Recommended Usage (Works …
=> [Fix for Webpack 2 Beta 24+] Get loader options from query instead of raw this.options

lib/loader.js, package.json, test/fixtures/css-modules.vue, test/test.js
@yyx990803 
2.x uses `vue-template-compiler`, which doesn't expose non standard props (`module`) on `<style>` tag.
Should we use `data-module` instead or modify `vue-template-compiler` to expose non standard props?
I prefer the later cause `scoped` was removed from standard.
=> [WIP]CSS modules

.gitignore, lib/loader.js, test/test.js
So that more options can be used instead of listing them specifically like `camelCase`.
And maybe there is no need to override the undefined localIdentName option which is passed customly.
=> use `Object.assign` to merge cssModules configuration `query` with `option`

lib/loader.js
* In Webpack 2 loaders have to be explicitly declared, the "-loader" part of their name is no longer implied.
This change assumes the use case where lang already ended with '-loader' is not typical or preferred.
=> [Fix for Webpack 2 Beta 26+] Explicitly declare inferred loaders by their full name (#464)

package.json, test/test.js
Fixes #488 . I normalized the line endings of the output to LFs to fix the issue where on Windows, CRLF line endings are generated and cause the unit tests to fail.
Also, the regexp for the scoped CSS ID wasn't correct-- apparently it doesn't always have to start with an `_`.  I discovered on Windows that I was getting some IDs that started with `E` for example.
=> Fix unit tests on windows

docs/en/features/css-modules.md
when i test , i add a keyword `module = "a"` to the style, i find that it is on the instance with `a` not `$a`
=> module="a"  => this.a

docs/en/features/css-modules.md
fix typos in css-modules.md
just make a small modification to it.
=> fix typos in css-modules.md

package.json, test/test.js
As of [ff5e94f](https://github.com/vuejs/vue-loader/commit/ff5e94fcd6b56ea3889a90c0c240a973c155dcff), this dependency is no longer needed.
=> Remove unused dependency

lib/loader.js, test/test.js
Improves the Vue.js devtools experience, no more “< Anonymous Component >”
=> When name isn’t specified use the filename as the component name.

lib/loader.js
解决在webpack中配置了babel的sage-x之后引起的Object.keys(__vue_script__).length === 2引起误报的问题
=> 使用10.x的named exports判断方式

docs/en/start/spec.md, lib/component-normalizer.js, lib/loader.js, test/test.js
if several unnamed components have the same filename, occured endless loop.
see #596
=> Revert default component name option

lib/loader.js
Reference (Reproduction repo too): #592 
In css modules, When we change styles, these styles can not set to Vue Instance due to cache of Vue Constructor.
I fixed this issue with using HMR API.
=> fix cannot set css modules to vue instance

lib/loader.js, package.json, test/fixtures/markdown.vue, test/test.js
This enables, for example, using a markdown loader via <template lang="md"> in a .vue file.  Without this tweak, the webpack config has to specify both the loader that converts the markdown (e.g.) to HTML **and** template-compiler to compile it.  That, however doesn't fully work because the webpack config can't know the moduleId generated by lib/loader.js and pass it in via the `id` parameter, so scoped styles won't work.
=> Add the vue template compiler onto any template loader specified in the vue.loaders configuration

docs/LANGS.md, docs/pt/README.md, docs/pt/SUMMARY.md, docs/pt/configurations/advanced.md, docs/pt/configurations/asset-url.md, docs/pt/configurations/extract-css.md, docs/pt/configurations/pre-processors.md, docs/pt/features/css-modules.md, docs/pt/features/es2015.md, docs/pt/features/hot-reload.md, docs/pt/features/postcss.md, docs/pt/features/scoped-css.md, docs/pt/options.md, docs/pt/start/setup.md, docs/pt/start/spec.md, docs/pt/workflow/linting.md, docs/pt/workflow/production.md, docs/pt/workflow/testing-with-mocks.md, docs/pt/workflow/testing.md
=> Translation into portuguese

docs/pt/README.md, docs/pt/SUMMARY.md, docs/pt/configurations/advanced.md, docs/pt/configurations/asset-url.md, docs/pt/configurations/custom-blocks.md, docs/pt/options.md
I'll be working around the updates.
=> [docs] Minor fixes and updates

docs/en/workflow/production.md
This was causing the following error:
webpack.optimize.OccurenceOrderPlugin is not a constructor
=> Change occurence to occurrence

lib/loader.js, lib/selector.js, lib/style-rewriter.js, lib/template-compiler.js, lib/template-loader.js, package.json
related:
https://github.com/webpack/loader-utils/issues/56
=> fix deprecated warning (close #666)

lib/parser.js
The pad option now accepts 'line' or 'space' as padding options.
Depends on vuejs/vue#5059, although the original check for `pad` is a truthy one, so this PR could be merged before that one with no trouble.
=> Update parser's call to parseComponent

docs/en/configurations/custom-blocks.md
It's not correct that `plugins` is wrapped in the `module`
=> [Docs]webpack.config.js is wrong

docs/en/configurations/advanced.md, lib/loader.js
here is the [issue](https://github.com/vuejs/vue-loader/issues/696)
=> [feature]About the hard-coded list of excluded loaders chained before vue-loader

lib/loader.js
Hi,
I think it should use `loaderUtils.parseQuery` to parse the result from regular expression.
Otherwise we can't get css-loader' query such like `...!css-loader?{"minimize":true}...` for css-module.
The last change RP: https://github.com/vuejs/vue-loader/commit/1d63e9ec610490767b447cee5cf53e00faf905fa
Thanks
=> fix parse cssModules loader query

docs/pt_BR/configurations/custom-blocks.md
Refs: https://github.com/vuejs/vue-loader/pull/664
=> [Docs] Updated

lib/style-compiler/load-postcss-config.js
Hey guys,
I found this small issue today after refreshing my node modules and pulling in a new version of vue-loader. I'm using Node v4.7.3 and it was throwing this error whilst compiling style blocks:
`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`
So, this tiny change is how I fixed it...pretty sure it's not going to break anything!
=> Change let to var

docs/en/workflow/production.md
The OccurrenceOrderPlugin enabled by default in Webpack 2
P.S.: Or maybe better to remove this from example?
=> Add note about OccurrenceOrderPlugin

docs/ru/configurations/extract-css.md, docs/ru/features/scoped-css.md, docs/ru/options.md, lib/loader.js
=> [JUST MERGE ME] Russian translation update

lib/component-normalizer.js, package.json, test/fixtures/functional-style.vue, test/fixtures/ssr-style.js, test/fixtures/ssr-style.vue, test/test.js, yarn.lock
Adds support for SFC components that have injectStyles. 
Example component: 
```
<script>
export default {
functional: true,
render(h, { children }) {
return h('div', children);
},
};
</script>
<style lang="scss">
@import 'style/settings';
@import 'style/tools';
@import 'style/components/wrapper';
</style>
```
Also does not apply hook to functional components, without injectStyles. I believe that this is not needed, correct me if i'm wrong.
=> [Fix] functional SFC style injection support

lib/loader.js, test/test.js
fix https://github.com/Microsoft/TypeScript-Vue-Starter/pull/3
If `extractCSS` is true, vue-loader will consult text extractor if loaders[lang] is not explicitly configured. This causes pug-loader and ts-loader malfunctions.
This PR makes extractCSS is only applied to styles.
=> fix: extractCSS should only be applied to styles

README.md
The link now points to webpack 2 instead of webpack 1
Fixes #829
=> Update webpack url

docs/en/workflow/testing-with-mocks.md
I recently updated a Vue app to Webpack 2 and the injector stopped working. It was difficult to diagnose the problem, until I realized that I had left the injector like in the example from the docs. Using `vue-loader` explicitly in the example works for Webpack 2 and should still (I think) work for Webpack 1.
=> Use `vue-loader` explictly when creating injector

docs/en/features/scoped-css.md
In 12.1 version deep selectors (`>>>` and `/deep/`) have been introduced but there is no info about that in the documentation.
=> Update scoped-css.md with info about deep selectors

package.json, yarn.lock
PostCSS plugins (like `postcss-nested` in my case) starts requiring a higher version of PostCSS.
=> Upgrade PostCSS to 6.0.1

docs/en/workflow/testing.md
From [phantomjs npm](https://www.npmjs.com/package/phantomjs):
> DEPRECATED
> Pre-2.0, this package was published to NPM as phantomjs. We changed the name to phantomjs prebuilt at the request of PhantomJS team.
> 
> Please update your package references from phantomjs to phantomjs-prebuilt
=> Use phantomjs-prebuilt instead of phantomjs

lib/loader.js
A very basic transformation from `require` to `import`, more work & help needed.
1. The use of `config.esModule`
I'm currently using this existing config as option for using `imports` instead of `require`s. Since it's undocumented, I'm not sure if this is a breaking change/it's suitable for this feature.
2. To-do: 
3. Mysterious webpack warnings that doesn't seem to be related to vue-loader
```
[12] ./node_modules/vue/dist/vue.runtime.esm.js 187 kB {15} {16} [built]
ModuleConcatenation (inner): dependency variables are used (i. e. ProvidePlugin)
```
4. Unpassed test: `vue-loader expose filename`, this one's failing on master too, probably not related to this PR
=> Support webpack 3 module concatenation by using `import`s instead of `require`s.

docs/en/configurations/advanced.md, docs/en/options.md
Some changes we have made from French documentation.
- Change all `>=` to `+` for consistency accross all Vue documentation.
Feel free to not accept point that not feet your needs for English documentation.
- Vue : https://github.com/vuejs/vuejs.org/pull/1025/
- Vue Server Renderer : https://github.com/vuejs/vue-ssr-docs/pull/106/
=> [Doc EN] — Several files — Consistency changes

docs/en/options.md
Change default value from `false` to `true` follow new behavior in `>13.0.0`
=> docs(options.md): Change default value of `esModule`

lib/loader.js, lib/template-compiler/index.js, test/fixtures/template-comment.vue, test/test.js
add a keyword ```comment``` to support  allow keep comments in sfc:  
```
<template comment>
<div>
...
...
</div>
</template>
```
=> support comment option in template

lib/style-compiler/load-postcss-config.js
We currently support postcss options being a function, but not options.plugins.
This should be mostly harmless -- I wanted to provide a test but we don't currently test support for any postcss plugin, do we?
=> Support postcss.options.plugins being a function

package.json, yarn.lock
This adds dependencies `link-staged` and `husky`. Configuration for `lint-staged` is added to `package.json` to run linter on staged files for `lib` and `test` folders. Can be kept as a separate file also. Let me know if you wish to do that.
=> Setup lint-staged pre-commit hook with husky

lib/template-compiler/modules/transform-require.js, test/fixtures/resolve.vue
Hi. Recently we encounter a problem with Nuxt usage of aliases inside `.vue` files. The problem is that if aliases begin with `~/assets/logo.png` they will work with normal webpack requires but `vue-loader` tries to convert them to something like `/assets/logo.png` which is not a valid path. This PR fixes this condition and also adds appreciate tests.
Related issues:
- nuxt/nuxt.js#1241
- nuxt/nuxt.js#1257
- [this](https://github.com/nuxt/nuxt.js/commit/1f85b2dd13622575dbf0d2569d7486152d261d13) discussion
=> fix(transform-require): support ~/ aliases

lib/selector.js
In chrome devtool
Before
After
=> keep path of source file in source map

docs/en/configurations/pre-processors.md, docs/ja/configurations/pre-processors.md, docs/ru/configurations/pre-processors.md
Replace the file path `build/util.js` by the correct `build/utils.js` of the [webpack template](https://github.com/vuejs-templates/webpack/blob/master/template/build/utils.js)
=> docs(EN,JA,RU): fix webpack template utils filename

docs/zh-cn/configurations/pre-processors.md
=> [CN] Added "Loading a global settings file"

docs/en/workflow/testing-with-mocks.md
since we use mocha&chai in our webpack template, it makes sense that the test examples use that syntax as well.
=> use chai syntax for mock test example

docs/zh-cn/SUMMARY.md, docs/zh-cn/options.md, docs/zh-cn/workflow/testing-with-mocks.md
ref: `/docs/en/*` parts of https://github.com/vuejs/vue-loader/compare/eb748f2...5e549cb
/ping @Justineo
=> [zh-cn] synced from #eb748f2 to #5e549cb

docs/zh-cn/features/functional.md
Checked out from #1012 as it's not updated for a while.
/cc @jasonwithjs 🙏
/ping @Justineo 
Thanks.
=> [zh-cn] improved #1012

docs/en/features/hot-reload.md, docs/en/options.md, lib/loader.js, lib/template-compiler/index.js, test/test.js
Implements disabling Hot Reload via loader's option
=> feat: disable Hot Reload option (#1036)

lib/style-compiler/plugins/scope-id.js, test/fixtures/scoped-css.vue, test/test.js
fixes https://github.com/vuejs/vue-loader/issues/1031
=> fix: scoping of multiple animations

docs/en/workflow/testing-with-mocks.md
1. Removed the unstable note about `inject-loader@3.x`.
2. Note for disabling `esModule` option in inject mode because `import/export` must be top-level.
Ref: #892 
Thanks.
=> [docs] updated status of inject-loader (close #892)

lib/template-compiler/modules/transform-srcset.js, test/fixtures/transform.vue, test/test.js
ref #1052 
The `srcset` is transformed wrong when there is no descriptor after image candidate string.
Thanks.
=> Fix #1052 about parsing 'srcset' attribute value

lib/style-compiler/plugins/scope-id.js, test/fixtures/scoped-css.vue, test/test.js
`animation-name` doesn't have to appear at the beginning of the `animation` shorthand.
=> Fix animation value replacement for scoped CSS

lib/loader.js
Removed the unnecessary string concatenation, though it's no error caused.
Generated code before this fix:
```js
/* hot reload */
if (module.hot) {(function () {
var hotAPI = require("vue-loader/node_modules/vue-hot-reload-api")
hotAPI.install(require("vue"), false)
if (!hotAPI.compatible) return
module.hot.accept()
if (!module.hot.data) {
hotAPI.createRecord("data-v-7ba5bd90", Component.options)
} else {
hotAPI.reload("data-v-7ba5bd90", Component.options)
' + '  }
module.hot.dispose(function (data) {
disposed = true
})
})()}
```
Thanks.
=> Small code fix for hot-reload

lib/loader.js
Ref: #1084 
Seems hashing the `shortFilePath` only is enough. But I am not sure whether the `content` is need to be hashed in production. So finally just concat them together and hash it all.
Thanks.
=> hash all filepath and content in production to fix #1084

lib/loader.js, test/fixtures/postcss-lang.vue, test/test.js
~~= Problem~~
~~- vue-loader automatically handles postcss by default, there is many issues
around using custom postcss lang option.~~
~~- Using postcss without a `lang` attribute causes SFC to loose syntax
highlghting~~
~~= Solution~~
~~- Enable option to alias langs to loader settings.~~
~~- specify `postcss` in lang and maintain default loader configurations~~
If no postcss loader is provided in vue loader options then default to
vue-loader handling
This allows you to use vue internal postcss/css handling with known
postcss extensions
fixes: #942
fixes: #800
fixes: #654
=> Feature: Handle postcss file extensions if no loader options give

package-lock.json, package.json
One of the packages (`marked@0.3.6`) that the latest version of vue-loader uses has a security vulnerability.
More information:
https://nvd.nist.gov/vuln/detail/CVE-2017-1000427
https://www.checkmarx.com/advisories/regular-expression-denial-service-redos-vulnerability-marked-npm-package/
https://nvd.nist.gov/vuln/detail/CVE-2017-17461
This PR update `marked` to the latest version.
=> update `marked` to the latest version

lib/template-compiler/index.js
`transformToRequire` is actually broken since v14 because compiler options is passed by `this._compilation.__vueOptions__`, instead of webpack loader option, so it should be `vueOptions.transformToRequire` here. 
Not sure why tests didn't fail for `options.transformToRequire` :/
=> fix: get transformToRequire from vueOptions instead of options for template-compiler (#1171)

lib/style-compiler/load-postcss-config.js, package.json, test/fixtures/sub/.postcssrc.js, test/fixtures/sub/postcss-cascade.vue, test/test.js
Just added a vue-loader config:
``` js
{
test: /\.vue$/,
loader: 'vue-loader',
options: {
postcss: {
cascade: true
},
// other vue-loader options go here
}
},
```
to load PostCSS config for each pieces of `<style>` code. But theoretically it will slow down the compilation.
Thanks.
Ref: #1063
=> Supported cascading postcss config

lib/loader.js
I have some older project still runnig on Vue 1 and crash on 'loader.charAt is not a function' error like in the #624 issue.
I am not javascript expert, but this edit solve my issue and maybe can solve also for other.
=> Fix for 'loader.charAt is not a function' in v8

docs/zh-cn/configurations/asset-url.md, docs/zh-cn/options.md, docs/zh-cn/start/spec.md
Ref: https://github.com/vuejs/vue-loader/compare/36276c0...b22db1d
/ping @Justineo 🙏
=> [docs][zh-cn] synced updates to v14.2

README.md, lib/index.js
With webpack 4, `this.minimize` value is `undefined`. This PR allows enabling `minimize` with loader options.
----
A side note from [here](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202):
> Guideline: Loaders should receive all options via this.query. They should not use other ways to receive options, i. e. no property in webpack options, no environment variable.
=> feat(loader): support options.productionMode

lib/index.d.ts, package.json
enable to work with `webpack.config.ts`
=> add .d.ts declaration file

lib/loaders/pitcher.js
Webpack's module concatenation support was broken by v15 due to this `module.exports` line. Changing to ESM export fixes this issue.
=> Fix webpack module concatenation support for v15

lib/index.js
=> fix: ignore VueLoaderPlugin check when using thread-loader for now

docs/zh/guide/README.md, docs/zh/guide/pre-processors.md, docs/zh/migrating.md, docs/zh/options.md
ref: https://github.com/vuejs/vue-loader/compare/1204381...544f08f
=> [docs][zh] update

lib/template-compiler/index.js
same as [fix: default parser was removed from prettier](https://github.com/vuejs/component-compiler-utils/pull/15)
=> fix: default parser was removed from prettier

lib/template-compiler/index.js
Since as of Prettier 1.13.0 there is no longer a default:
prettier/prettier#4528
The `parser` option has been supported since prettier v0.0.10, so this won't break users whose lockfile still references a pre-1.13.0 release of prettier:
https://github.com/prettier/prettier/blob/1.13.0/src/main/core-options.js#L89
This is the `v14` branch backport of:
vuejs/component-compiler-utils#15
Whilst #1322 is the more important PR for us, since it will help fix the Neutrino 8 (stable) branch, this PR:
* fixes Neutrino `master` (which is still using vue-loader 14 until we have a chance to update to v15),
* prevents the inconsistent situation where the error is fixed on vue-loader v13 and v15, but not v14.
=> [v14] fix: Explicitly set the prettier parser to 'babylon'

lib/plugin.js
`cnpm` (which using npminstall) install the package to the directory like:
```
~project/node_modules/_vue-loader@15.2.1@vue-loader
```
it test false using `/^vue-loader|(\/|\\)vue-loader`
=> fix: check loader for cnpm(npminstall)

lib/codegen/customBlocks.js
When using `src` attribute on custom blocks, the requested file won't be able to know which file is actually requesting it, maybe we can directly inject `resourcePath` to the query as a workaround.
=> Inject issuerPath to resourceQuery for custom blocks

docs/options.md, docs/zh/options.md, lib/loaders/pitcher.js
When `cacheIdentifier` contains exclamation mark `!`, the `!` would be treated as the separator between different loaders. which will cause unexpected compilation error.
e.g.
when you have these options set:
```
{
cacheIdentifier: 'a!a=1'
}
```
You would get following error:
```
Module not found: Error: Can't resolve 'a=1-vue-loader-template"}' in '/Users/haolchen/Documents/__self__/__forked__/vuepress/docs/guide'
@ ./docs/guide/deploy.md?vue&type=template&id=7ff0bdcd 1:0-324 1:0-324
@ ./docs/guide/deploy.md
@ ./lib/app/.temp/routes.js
@ ./lib/app/app.js
@ ./lib/app/clientEntry.js
@ multi ./lib/app/clientEntry.js
```
This PR is to replace all the `!`s in `cacheIdentifier`, and document that `cacheDirectory` path cannot contain `!` (We cannot replace the `!`s in `cacheDirectory`).
refs: …
=> fix unexpected error when options of cache-loader contains !

lib/codegen/customBlocks.js, lib/codegen/styleInjection.js, lib/index.js, test/advanced.spec.js, test/mock-loaders/query.js, test/utils.js
**What kind of change does this PR introduce?** (check at least one)
**Does this PR introduce a breaking change?** (check one)
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**Other information:**
I am working on a loader that compiles markdown into a Vue component and also extracts all Vue code-blocks into demos. I do this by creating a mddemo-loader that extracts the particular demo by an index passed into the query (eg. `idx=0`). The output of this loader is piped into vue-loader. However, vue-loader currently doesn't inherit the existing queries so the mddemo-loader doesn't get applied (via webpack config) and the entire markdown is gets parsed when …
=> Inherit existing queries

docs/guide/testing.md
It looks like the `/en` segment of the url changed, these old links returned 404s
=> Fix broken links

docs/guide/linting.md, docs/ru/guide/linting.md, docs/zh/guide/linting.md
=> Add doc for `stylelint`

lib/index.js, test/advanced.spec.js, yarn.lock
Combined with [this change](https://github.com/vuejs/vue-component-compiler/commit/541a82483d4ea44b010e2394a65875819a094ad0) in vue-component-compiler, this will allow names to be inferred for _all_ `.vue` files, even those precompiled for production. That means 3rd-party component libraries will never have to define names if they're using `.vue` files! 🙂
We've also made [this change](https://github.com/vuejs/vue-devtools/pull/714) in the devtools, so that we don't allow users to open a file if we only have the basename instead of the full path.
=> Set __file to file basename in production

lib/select.js, test/style.spec.js
Improve the debugging experience for `<script>` in the `.vue` file by append the type extensions to the end of files in devtools, to make file locate easier.
Result:
=> feat: #1371 Append the file extension to the mapping files in devtools

lib/index.js, test/advanced.spec.js
**What kind of change does this PR introduce?**
Bugfix
**Did you add tests for your changes?**
Yes, I updated [the existing test](https://github.com/vuejs/vue-loader/blob/0c2da0f5bacb8d0c392fd78b1a3ac72f46bc9ee5/test/advanced.spec.js#L49-L56) to reflect the desired value.
**If relevant, did you update the README?**
No.
**Summary**
When using this loader on a project where we have Windows, Linux (and maybe OS X) users,
I discovered we were getting different bundles if one user bundled using a POSIX system, and another user bundled **the same files** on a Windows system.
I only encountered this issue when building **in development mode**.
**Does this PR introduce a breaking change?**
No.
=> Fix inconsistent path between Windows and POSIX systems‏

lib/loader.js, lib/parser.js, test/test.js
The back slash should be replaced with the slash for consistent hash.
=> Fix the snapshot testing issue on windows

docs/guide/README.md, docs/ru/guide/README.md, docs/zh/guide/README.md
I guess this is some leftover which is no longer needed.
=> docs: remove unnecessary `path` module usage

docs/options.md, docs/zh/options.md, lib/loaders/templateLoader.js, package.json, test/fixtures/prettier-bug.vue, test/template.spec.js, yarn.lock
=> feat: add `prettify` option

lib/codegen/styleInjection.js, test/advanced.spec.js, test/fixtures/empty-style.vue, test/fixtures/extract-css-chunks.vue
As addressed in https://github.com/vuejs/vue-cli/issues/3165, do not generate empty chunk css files for component only contains empty style tag.
=> fix: avoid to generate empty css chunk files

lib/loaders/pitcher.js
Windows will generate different hash because the '\' will be formatter to '//' by `JSON.stringify`
Please fix it to confirm generate consistent hash.
```
// CONCATENATED MODULE: ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules//.cache//vue-loader",
```
=> fix: template comments replace windows \ to / confirm consistent hash

docs/options.md, lib/index.js, test/advanced.spec.js
See https://github.com/vuejs/eslint-plugin-vue/issues/265#issuecomment-449815045
I still think this should be off by default and automatically turned on for `lib` target in Vue CLI, rather than the other way around.
Actually, the `__file` property is not commonly needed even for component libraries in production.
For example, there're several popular frameworks that use hard-to-infer folder structures:
- https://github.com/ElemeFE/element `packages/alert/src/main.vue`
- https://github.com/airyland/vux `src/components/video/index.vue`
They are not going to benefit from this feature.
Other frameworks, like [buefy](https://github.com/buefy/buefy/blob/dev/src/components/autocomplete/Autocomplete.vue) & [Keen-UI](https://github.com/JosephusPaye/Keen-UI/blob/024f6836f9517a036a36d07f17b74af0d8629 …
=> feat: make `__file` injection opt-in in production

lib/template-compiler/index.js, package.json
babylon has been deprecated... Deprecation message when building:
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
=> Replaced babylon per babel

lib/loaders/templateLoader.js
Like #1208 we need to use `productionMode` option for template loader too.  Related to nuxt/nuxt.js#4002.
=> fix(templateLoder): honor options.productionMode

.gitignore, lib/loaders/pitcher.js, package.json, test/custom.spec.js, yarn.lock
fix #1394 
I've simply ignored if custom block does not have other loaders than `cache-loader` and `vue-loader`. I'm not sure if there is better way to fix this issue but it just works.
=> fix: avoid generating custom block when there is only cache-loader

lib/codegen/styleInjection.js, test/fixtures/basic.vue
In https://github.com/vuejs/vue-loader/pull/1464, after filtering styles, the indexes of styles are changed. Which makes `index` in the request query incorrect.
close https://github.com/vuejs/vue-cli/issues/3449, https://github.com/vuejs/vue-cli/issues/3165
=> fix: keep style index consistent when filtering styles

lib/loaders/pitcher.js, test/template.spec.js
I know there is already a MR that sorts this issue out but I think bringing the `postLoader` option back is not the best approach to solve this issue. This merge request proposes a solution that allows post loaders to be applied after the template loader with no extra options.
**Motivation**
In our project we would like to be able to execute a custom `babel-macro` in our templates and that requires us to process the compiled template using babel. Currently the v15 does not allow this. See: #1309.
**Description**
The solution implemented in this merge request detects which loaders have `enforce: 'post'` option looking at the `pitchExecuted` flag in the loader object. Once the `VueLoaderPlugin` injects the pitcher at the beginning of the loaders list that means the pitcher's `pitch` would …
=> Support post loaders for template blocks

test/fixtures/multiple-roots-template.vue, test/template.spec.js
add regression test for https://github.com/vuejs/vue-loader/issues/1491 "Multiple root nodes throwing RangeError instead of Component template
should contain exactly one root element"
seems the Issue itself is already fixed?
I checked it only with the dependencies of the lock file, maybe they are outdated?
Anyway, I hope the added Test is helpfull
=> add regression test for #1491

lib/index.d.ts, package.json, yarn.lock
This PR essentially adds the interface `VueLoaderOptions` that can aid type checking
when writting Webpack configuration with Typescript:
```ts
// webpack.config.ts
import { VueLoaderOptions, VueLoaderPlugin } from 'vue-loader'
export default {
module: {
rules: {
// ...
{
test: /\.vue$/,
loader: 'vue-loader',
options: {
// * autocompletion available here *
} as VueLoaderOptions
}
}
},
plugins: [
new VueLoaderPlugin()
]
}
```
I'm studying the possibility of using a [discriminated union](https://www.typescriptlang.org/docs/handbook/advanced-types.html#Discriminated-Unions) to assign the `options` type when a match `loader: 'vue-loader'` is found, but this will come in a later PR. For now the casting on the options object is required.
---
Please note the compiler interface use types that …
=> types: add loader options declarations

lib/codegen/hotReload.js
We should not use `module.hot.data`, which is highly non-reliable. Plugins like [lazy-compile-webpack-plugin](https://github.com/liximomo/lazy-compile-webpack-plugin) use a dummy loader to prevent webpack from building async modules, the module will be compiled and hot-update on demand.  In such a case, the `module.hot.data` is truthy but the record does not exist, which will cause a running error in `api.reload`. I think `api.isRecorded` is more reliable and reasonable.
=> fix: use "api.isRecorded" instead of "module.hot.data"

lib/loaders/pitcher.js
Similar to https://github.com/vuejs/vue-cli/pull/4532 - third-parties declaring loaders are strongly advised to use `require.resolve` to ensure they correctly reference their own dependencies.
=> Uses require.resolve

docs/guide/pre-processors.md, docs/ru/guide/pre-processors.md, docs/zh/guide/pre-processors.md
fix docs with error: 'options has an unknown property 'indentedSyntax'.'
which new sass-loader are writen in 'sassOptions';
This should also cause quick prototyping's sass setting, after executing '$vue serve'
=> docs: add `sassOptions` for sass-loader >= 8 (#1593) [ci skip]

package.json
Allow user to run `npm repo vue-loader` and remove warn running `npm`.
=> Add missing `"repository"` field in package.json

lib/plugin-webpack4.js, lib/plugin-webpack5.js
This PR adds support for [nested rules](https://webpack.js.org/configuration/module/#nested-rules) using [Rule.rules](https://webpack.js.org/configuration/module/#rulerules).
=> Fix Rule.rules (nested rules) not supported

package.json, test/utils.js
`memory-fs` is deprecated, switch over to `memfs`.
=> chore(deps): migrate to memfs

lib/runtime/componentNormalizer.js
Add fetching `$root` from parent because functional components' context doesn't have the `$root` property. It will close [issue](https://github.com/vuejs/vue-cli/issues/4097).
=> fix getting shadow root when component is functional

src/index.ts
Hi!
Fixes an edge case: if you have multiple `style` and the *2nd* one is a `module`, it will cause a build failure:
```
<style lang="css">
</style>
<style module>
</style>
```
Internally, this builds:
```js
import "./App.vue?vue&type=style&index=0&lang=css"const cssModules = script.__cssModules = {}
import style1 from "./App.vue?vue&type=style&index=1&module=true&lang=css"
cssModules["$style"] = style1
```
Notice the missing line break before `const cssModules =`.
Apologies for no test... but I can't seem to find any for `next` :).
Cheers!
=> bug: (next) Missing line break before const cssModules causes module load error

src/pluginWebpack4.ts, src/pluginWebpack5.ts
I'm developing a prototype of vuepress-next
For `.md` files, the template loader won't take effect with `test: /\.vue$/`.
Add an option for `VueLoaderPlugin` to make the test rule customizable.
=> fix: do not require vue extension for template loader

.circleci/config.yml, package.json, src/index.ts, src/pitcher.ts, src/plugin.ts, src/pluginWebpack4.ts, src/pluginWebpack5.ts, src/select.ts, src/stylePostLoader.ts, src/templateLoader.ts, test/core.spec.ts, test/fixtures/basic.vue, test/fixtures/entry.js, test/utils.ts, yarn.lock
This change fixes the emitted TypeScript type definitions
Closes #1667.
=> refactor!: replace module.exports with ES module export

src/pluginWebpack5.ts
skip matching rules with 'enforce'.
eg. the rule of eslint-loader is before the rule of vue-loader, will throw this error: '[VueLoaderPlugin Error] No matching rule for .vue files found.'
=> fix: skip matching rules with 'enforce'

src/index.ts, src/templateLoader.ts
So that all the options are serializable and can be used with
thread-loader.
Fixes #1705
Fixes https://github.com/vuejs/vue-cli/issues/5723
=> feat: allow `compiler` option to be a path to the compiler module

docs/guide/pre-processors.md, docs/ru/guide/pre-processors.md, docs/zh/guide/pre-processors.md
Option `prependData `should be renamed `additionalData` in `vue.config.js` as per [sass-loader v9.0.0 changelog](https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0) and corresponding [doc](https://github.com/webpack-contrib/sass-loader#additionaldata).
=> docs: 'prependData' option renamed to 'additionalData' in sass-loader 9

lib/index.js
Id will affect the hash calculation of webpack, thus affecting the final cache
=> fix: Fix id differences between different operating systems

src/index.ts
when bindings pass as a query string, should not be `"undefined"` string value.
=> fix: fix script bindings should not be a  undefined value

lib/loaders/pitcher.js
In webpack 5 + mini-css-extract-plugin you'll see warning about a missing default export. This happens because vue-loader always assumes a default export for style blocks. This only happens in the case of CSS modules.
Closes #1742
=> Fix missing default export error

src/pitcher.ts
In webpack 5 + mini-css-extract-plugin you'll see warning about a missing default export. This happens because vue-loader always assumes a default export for style blocks. This only happens in the case of CSS modules.
This is the same as #1748 but for vue-loader 16
=> [next] Fix missing default export error

lib/plugin-webpack5.js
Webpack 5 has a new property in rule definitions called `generator` - we need to account for that in the rule validiations we have in place.
**Note** this is for vue-loader 15, targeting Vue 2. Matching PR for v16: https://github.com/vuejs/vue-loader/pull/1754
I wasn't sure how to test for this as the repo's webpack version is locked to v4, and the property only exists in v5.
I locally changed the webpack version to v5, added the following rule to the test cases base config and ran the tests:
```js
{
test: /\.tiff$/,
type: 'asset/resource',
generator: {
filename: '[hash][ext][query]'
}
}
```
... multiple tests broke without my change, and all tests passed after my change.
close #1729
=> fix: ensure new webpack5 generator property in rules passes ruleset checks (v15)

src/pluginWebpack5.ts
Webpack 5 has a new property in rule definitions called `generator` - we need to account for that in the rule validiations we have in place.
**Note** this is for vue-loader 16, targeting Vue 3. Matching PR for v15: https://github.com/vuejs/vue-loader/pull/1753
I wasn't able to test this with v16, as the repo is locked to webpack v4, and switching tempararily to webpack 5 breaks everything as the type imports for webpack no longer work/match.
Since I could verify the change on the other PR for v15, this should be safe to merge.
close #1729
=> fix: ensure new webpack5 generator property in rules passes ruleset checks (v16)

src/index.ts, src/resolveScript.ts, src/templateLoader.ts
This option provides a possible fix for #1734
When testing with mocha + mochapack, even though the target
environment is `node`, the compiled component is expected to be run
with `jsdom` rather than with a Node.js server, so it should still be
a client bundle.
=> feat: allow manualyl specifying whether server-rendering is targeted

src/resolveScript.ts
when using `<script setup>`:
`vue-loader: resolveScript` -> `compiler-sfc: compileScript` -> `compiler-sfc: compileTemplate`.
`compileTemplate` should receive and merge `options.templateOptions.compilerOptions` which `resolveScript` had not pass in `templateOptions`.
pass `templateOptions.compilerOptions` to `compileScript` in `resolveScript`.fix #1838 .
=> fix: pass compilerOptions to compileTemplate when enable inline, fix #1838

package.json
**What's the problem this PR addresses?**
`vue-loader@16` depends on `webpack` and `@vue/compiler-sfc` but doesn't declare it
Fixes https://github.com/vuejs/vue-loader/issues/1844
**How did you fix it?**
Added `webpack` and `@vue/compiler-sfc` as peer dependencies
=> fix: add undeclared peer dependency `webpack` and `@vue/compiler-sfc`

src/exportHelper.ts
vue-loader not registering "__hmrId" on the correct component property
when component is created with vue-class-component.
This leads to vue/compiler-sfc/runtime-core/src/render.ts mountComponent()
function to not call registerHMR() on the instance (because __hmrId is not
attached properly):
```js
if (__DEV__ && instance.type.__hmrId) {
registerHMR(instance)
}
```
Not registering for HMR means the createRecord() map will never get injected
any component instances, so when module.hot.accept() + api.rerender(id, render)
are called they will not apply any update due to finding no instances:
```js
module.hot.accept("./Index.vue?vue&type=template&id=4bc9d7de&ts=true", () => {
console.log('re-render')
api.rerender('4bc9d7de', render) // will never do anything; instances === []
})
```
This …
=> fix: HMR not working correctly with vue-class-component components

src/index.ts, test/fixtures/custom-query.vue, test/script.spec.ts
Currently we simply append any existing `resourceQuery` to the end of any generated query string. In the event of a custom query being passed this leads to an invalid query, such as:
```js
const scriptQuery = '?vue&type=script&lang=js?custom=true'
const templateQuery = '?vue&type=template&id=49803768?custom=true'
const styleQuery = '?vue&type=style&index=0&id=49803768&lang=css?custom=true'
```
The four locations where this happens are:
https://github.com/vuejs/vue-loader/blob/6dce21e555c28a47f19a13bbe9fa4fa86b2dfc69/src/index.ts#L159
https://github.com/vuejs/vue-loader/blob/6dce21e555c28a47f19a13bbe9fa4fa86b2dfc69/src/index.ts#L179
https://github.com/vuejs/vue-loader/blob/6dce21e555c28a47f19a13bbe9fa4fa86b2dfc69/src/index.ts#L199 …
=> fix: merge custom queries rather than appending

src/descriptorCache.ts, src/formatError.ts, src/index.ts, src/resolveScript.ts, src/stylePostLoader.ts, src/templateLoader.ts
This PR fixes this issue #2031. These changes are important in situations where one is only interested in using the loader to compiler the SFCs but not dependent on Vue itself (custom renderer projects).
=> fix: reference project compiler, fixes #2031

.github/workflows/ci.yml, README.md, jest.config.js, package.json, src/index.ts, src/pitcher.ts, src/plugin.ts, src/pluginWebpack5.ts, src/util.ts, test/advanced.spec.ts, test/edgeCases.spec.ts, test/style.spec.ts, test/template.spec.ts, test/utils.ts, tsconfig.json
This PR leverages inline match resource, a new technique provided by Webpack@5 
to process modules, which allows loader developers to write more ergonomic code
and make the code easier to maintain. From now on, you can enable 
`options.experimentalInlineMatchResource` of `vue-loader` to give it a try.
Other minor changes: 
1. Dispatch `VueLoaderPlugin` dynamically to decouple webpack and support webpack-like plugin systems.
2. Webpack@5 `experiments.css` support
Note:
The ideal solution with inline match resource is to get rid of the `VueLoaderPlugin` completely, 
I will try to optimize this in the future.
=> feat: support experimental inline match resource

src/pitcher.ts
Escape windows path for fixing `experiments.css`.
=> fix: windows path for `experiments.css`

src/stylePostLoader.ts, test/core.spec.ts, test/template.spec.ts
So the loader `vue-loader/dist/stylePostLoader.js` can be used for pre-compiled Vue component files to handle scoped style imports.
e.g. in a Vue CLI project, you can just add these lines of code to make it work:
```js
const { defineConfig } = require("@vue/cli-service");
module.exports = defineConfig({
...
chainWebpack: (config) => {
const ruleNameList = ["css", "scss", "sass", "less", "stylus"];
ruleNameList.forEach((ruleName) => {
const rule = config.module.rule(ruleName);
rule
.oneOf("normal")
.use("style-post-loader")
.loader("vue-loader/dist/stylePostLoader.js");
});
return config;
},
});
```
...which would be great to be put into the default config of Vue CLI, despite it being out of maintenance.
Similar feature PR to Vite Plugin Vue: …
=> feat: skip normal css files without scoped flag in stylePostLoader

src/pluginWebpack4.ts, test/edgeCases.spec.ts
Webpack 4 uses `ident` query param underneath to store `options` objects passed to loaders, and relies on  this `ident` param to retrieve `options` for correct loaders https://github.com/webpack/webpack/blob/v4.46.0/lib/RuleSet.js#L560-L566
Logic of "identing" is pretty straightforward - if `ident` is provided in `options` - that one [is respected](https://github.com/webpack/webpack/blob/v4.46.0/lib/RuleSet.js#L396), but if there is no `ident` - it is [generated](https://github.com/webpack/webpack/blob/v4.46.0/lib/RuleSet.js#L110) based on index of rule in RuleSet
vue-loader [heavily modifies](https://github.com/vuejs/vue-loader/blob/1b1a195612f885a8dec3f371edf1cb8b35d341e4/src/pluginWebpack4.ts#L99-L105) rules **after** `normalizeRules` kicked in and put `ident`'s for existing rules here …
=> fix: re-use ident of vue rule for template compiler, fixes #2029

.github/workflows/ci.yml, lib/codegen/customBlocks.js, lib/codegen/styleInjection.js, lib/codegen/utils.js, lib/index.d.ts, lib/index.js, lib/loaders/pitcher.js, lib/plugin-webpack5.js, lib/plugin.js, package.json, pnpm-lock.yaml, test/advanced.spec.js, test/edgeCases.spec.js, test/ssr.spec.js, test/style.spec.js, test/utils.js
I think vue-loader@15.x supports webpack5 experiments.css just as important, there are many people who use vue2.x, you might consider this pr @sodatea
=> feat: v15 support experimental inline match resource

package.json, src/index.ts, test/utils.ts, yarn.lock
Replace `hash-sum` with the same algorithm that `@vite/plugin-vue` does for scoped id.
~~Note: there are 2 test cases failed which need a further look.~~
Thanks.
=> chore: refactor hash()
